---
databaseChangeLog:
  - include:
      relativeToChangelogFile: true
      file: tag-visibility-workaround.yaml
  - changeSet:
      id: root-tag
      author: surabujin
      changes:
        - tagDatabase:
            tag: history-starting-point
  - include:
      relativeToChangelogFile: true
      file: 000-per-isl-bfd-properties.yaml
  - include:
      relativeToChangelogFile: true
      file: 001-rework-flow-multitable-flag.yaml
